name: Maven CI on Windows with JDK 21

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21 (Temurin)
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom1.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Run Linter (Checkstyle)
      run: mvn checkstyle:check

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test
